---
output:
  pdf_document: default
urlcolor: blue
---

30.5.2024

OK, grem čez 1_Macro_PROD.R od Katarine. Plan je popeglat in predvsem na koncu namesto v access zapisati v postgres bazo, kjer moram še pripravit tabele. Ampak gremo najprej čez kodo. 

Pazi, da je nov eurostat naložen, s starejšo verzijo ni delalo. 
Dodam opise spremenjljivk iz Eurostata, drugače nič ne razumem, pa za dokumentacijo je treba to vedet. Aja, `label_eurostat() ` je fajn.

GDP in EMP downloada za različne geo, pri GDP manjka eu28, ampak je 27 podvojen. Ravno tako pri GDP ni UK, pri EMP pa je. konsolidiram oboje. 

Datum pri EMP je do 2022, pri GDP do 2023, konsolidiram oboje in prestavim time range na začetek. 

V bistvu ima `get_eurostat()` že možnost filtrov, tako da nima smisla downloadat cele bulk tabele, če lahko že tam filtre nastavim, tako da gremo raje tako. 

ok, gremo naprej, kode držav delam bolj pregledne, country_code_EA_noIE je po moji logiki euro brez irske? ampak irska je not, ni pa hrvaške? to je za preverit. Roti potrdila, vržem ven IE in dodam HR

Naslednji korak je dodajanje aggregatov za neki skupin držav, kar se ponovi za vse 3 tabele, zato naredim raje funkcijo. 

OK, clean up kode je končan, zdaj pa samo še imena stolpcev, potrjena s strani Rotije.

CP_MPPS_EU27_2020_B1GQ	BDP, tekoče cene, v mio SKM (EU27 od 2020)
CLV10_MEUR_B1GQ	BDP, stalne cene leta 2010, v mio EUR
THS_PER_EMP_DC	Skupna zaposlenost, domači koncept, v 1000 oseb
 THS_HW_EMP_DC	Delovne ure, domači koncept, v 1000
THS_PER_POP_NC	Št. Prebivalcev, nacionalni koncept, v 1000
GDP_PC_PPS 	BDP na prebivalca v SKM
PROD_PPS 	Produktivnost v SKM, na zaposlenega
PROD_PPS_HW	Produktivnost v SKM, na delovno uro
PROD_real  	Realna produktivnost, na zaposlenega
PROD_real_HW  	Realna produktivnost, na delovno uro
EMP_RATE	Delež zaposlenih v celotnem prebivalstvu
HW_EMP  	Delovne ure na zaposlenega
GDP_PC_PPS_EU27_100	BDP pc v SKM (indeks EU27 2020 = 100)
PROD_PPS_EU27_100 	Produktivnost v SKM (indeks EU27 2020 = 100), na zap.
PROD_PPS_EU27_100_HW	Produktivnost v SKM (indeks EU27 2020 = 100), na delovno uro
EMP_RATE_EU27_100 	Stopnja zaposlenosti (indeks EU27 2020 = 100)
GDP_PC_PPS_EU27_100 	Delovne ure na zap. (indeks EU27 2020 = 100)

Evo, za konec še na hitro na lokalni bazi testno naredim tabelo in zapišem, vse dela super. 

# 3.6.2024

Started on the documentation in `umar_produktivnost-tehnična_dokumentaciona.Rmd`. 

Actually let's add the tidy version of the table as well, which means removing the original aggregates, but adding columns for each aggregation. Or maybe adding a table with the aggregations, to keep things normalised. 

OK, created `00_geo_lookup.R` where the lookup table is created. Also added EA20, cuz it didn't exist in the original set. The question is whether the tidy table should include teh country grouping columns, which would be familiar to people or not. I wonder if anyone will even use this ever, so maybe not, cuz that's clean af. 

Lemme check the aggregations tho. I mena compare the eurostat ones with mine. 

# 4.6.2024

OK, got the OBDC connection to the database to work on the new computer and added the instructions to the technical documentation. 

# 6.6.2024

OK, dodajam  še demo_pjan, za dekompozicijo bdp na preb z delovno aktivnim preb. tu je problem, ker se total ne sešteje enako kot prebivalstvo po nacionalnem konceptu. bomo probal oboje, da vidimo kolk je sploh ta razlika. 

OK, gremo gledat najprej te razlike med eurostat agregati in izračunanimi. EU28 in EU15 sta v bistvu passe, ker se končata 2020, tako da vprašanje, če se še uporabljajo. Isto EA19 verjetno, ki ga še računajo, ampak EU27 pa je verjento najbolj aktualen, ampak se razlikuje od izračunanega. Roti in Urška č pravita, da je samo EU20 relevanten. 


# 10.6. 

OK, zdej soem dodala še dekompozicijo po working age population, ker so podatki iz druge tabele je v dokumentaciji tudi analiza razlik. 

Trenutno zapisujem na lokalno bazo, ampak to se hitro prestavi, ko dobijo drugi driverje, da sploh laho dostopajo. 

Tabela produktivnost_makro je postavljena, tako da gremo na naslednjo skripto i guess?

Aja, dodala še geo lookup tabelo in v produktivnost marko stolpec aggr, da veš katere so ne-agregirane.

OK, 2. skripta. Združila dve tabeli share shift dekompozicije na zaposlenega in na delovno uro. In mal preimenovala spremenljivke, zato da so lahko skupaj, in da so konsistentne. In dodala še vsoto statične in dimanične strukturne spremembe. In tabela je v bazi tudi. 

ok, dejmo prestavit zdej to na produkcijo in dat Roti in Urški username-e. 

```
SELECT current_database();
SELECT current_database();
CREATE USER rotija WITH PASSWORD 'xxx';
CREATE USER urska_cede WITH PASSWORD 'xxx';

-- Grant usage on the schema
GRANT USAGE ON SCHEMA produktivnost TO rotija;
GRANT USAGE ON SCHEMA produktivnost TO urska_cede;

-- Grant select on all current tables in the schema
GRANT SELECT ON ALL TABLES IN SCHEMA produktivnost TO rotija;
GRANT SELECT ON ALL TABLES IN SCHEMA produktivnost TO urska_cede;

-- Ensure future tables inherit these permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA produktivnost GRANT SELECT ON TABLES TO rotija;
ALTER DEFAULT PRIVILEGES IN SCHEMA produktivnost GRANT SELECT ON TABLES TO urska_cede;
```

OK, zdej rabim še IP-je, Urška je 172, potem pa tud še domače, ampak ok, otom potom. 

# 12.6.

OK, gremo dokumentirat tale shift share. 

Ah, nace aggregates so 3 nivoji, dajmo to ločit. OK, dodala stolpec, da se loči te agregatne nivoje med sabo. V bistvu kasjeje Katarina tudi doda ene skd grupacije, zakaj jih ne bi že zdej za te dekompozicije? In tud agregacije za geografije ima dodane samo za zadnjo tabelo, pa ni razloga, da jih ne bi tudi že zdaj. OK; namesto treh tabel bo samo ena. 

Za skd agregacije naredim novo skripto `00_skd_lookup.R`. 

OK, dokumentacija za shift share, pain in the but, ampak mislim, da je. Bom dala Urški, da pregleda. 

Pa preselim mapo na O:avtomatizacija. 

# 13.6.

OK, gremo 3. skripto. popravljam v glavnem samo, da se drži iste sktrukture kot prejšnji dve. 

Aja, v bistvu 3. je rulc letno, ne surs, tisto dejmo na koncu. 

Tukaj sta dva dela, en s totali in en po skd. prvi je iz `nama_10_gdp`, drugi pa `nama_10_a10`.

OK, 3 skd sem naredila, ampak na oko so podatki na 3, 4 decimalki drugačni kot nazadnje shranjeni v access - in to za 1995, kar se valda ne spreminja? jutri naprej. Aha, prav je, isto dobim s Katarinino skripto, tako da so spreminjal neki očitno. 

# 17.6.

Vprašanja za Rotijo/Urško
-	Letne podatke sem dala z letnico (1995) in ne datumom (1.1.1995), je to OK?
- RULC podatki imajo indekse izračunane za 2005, 2007 in 2008 bazna leta, a so te letnice še vse relevantne, ali ni dodali kakšne druge?
- RULC četrtčetni totals so za seasonaly adjusted in NSA, NACE pa samo za NSA. 
- RULC totals so z BDP-jem, rulc NACE pa z DV-jem?
- Rulc letni totals imajo poleg sredstev za zaposlene tudi plače in prispevke in pri zaposlenosti tudi samozaposlene, medtem ko pri NACE tabeli ni plače in prispevkov, niti samozaposlenih. Jih dodam vseeno?



ok, končala četrtletnega tudi, ena napakica pri Katarini pri rename-u na koncu. 

OK, nenavadno, včasih dbexecute, ki ima create table in je time date, ne dela prav in time rata int. ne razumem zakaj. če isti sql poženem direkt iz dbeaverja, pa dela ok. 

Našla napako v trojki, DV rename namesto BDP. Bom naredila kar dva stolpca z imeni indikatorjev, da so konsistentni z ostalimi tabelami. 

OK, trojka narejena, dokumentirana. mal sem preimenovala tabele, upam, da sem povsod prav napisala. 

OK, začela peglat rulc total četrtletni. mal preveč vrstic ma zgleda, naslednji teden naprej.. 

# 24.6.2024

ok, se pravi imena indikatorjev dodat v štirki pa to. OK, to je narejeno in dokumentacija dodana. 
Gremo zdej še surs narest. 

# 26.6.2024

OK, v sursu, K. uporabi zoo funkcijo as.yearqtr, ki doda presledek ampak je tud nek class očitno, ne vem a je to potrebno in zakaj tega pol ni v ostalih četrtletnih skriptah.

Ta skripta je tako konfuzna, jao. OK, mamo DV, zaposlenost in stroške. dv + zap je produktivnost. dv ima dve meritvi, zap pa štiri. se pravi produktivnost jih ima šest pol. 

stroski imajo samo eno. potem obema, str in prod popraviš skd oznake na kratke. in pobrišeš dodatne stolpce. in ju daš skupaj - join. 1404 vrstic trenutno. to je zdej rulc .

na tej točki narediš sektorjske agregate (menjalni, poslovni) ampak K to naredi samo na produktivnosti for some reason. in preračune tudi. se pravi v tabeli brez stroškov dela. čeprav je že naredila rulc tabelo. prod tabela je široka, v resnici je to shift share tabela, če prav vidim. ok, to bomo naredil z istimi imeni stolpcev kot so že v shift share.

za rulc potem tud naredi agregate sektorske in hkrati še BCDE minus C = BDE. česar na ni pri shift share-u. bomo še tam dodali. 

jesus 0300220S.px je ful glupa tabela, kao dodana vrednost po SKDjih, in potem je še ena serija za skupaj in na koncu še BDP, seveda skupaj. ampak wtf nej s tem počne človk. Pa zmedlo me je, ker ga Katarina ni eksplicitno ven vrga, in ji pade ven šele z merge-om z zaposlitvioj. 

# 1.7.2024

fuck, problem s temi sursovimi tabelami je, da niso tidy, ker imajo not BCDE in C, kar je cela jeba pol, ko hočem recimo menjalne grupirat. moram za surs nove grupe narest očitno.. 

rotijo vprašala za imenovanje spremenljivk. damo emp in hw na konec in real in nom na sredino. spremenljivka pa je spredi. 

ok, končala shift share in rulc četrtletno

sem pa preimenovala vse spremenljivke in moram to zdaj popraviti še na 02, 03 in 04. 

# 2.7.24

OK, naredila skripto 2, dodala par spremenljivk, da je isto kot pri sursu, preimenovala in popravila sql in dokumentacijo. 

gremo 3. ok, letne BDP in letne VA narejene. 4. tudi. in dokumentacija je vsa ok. samo še preverit je treba cifre na hitro.

OK, 5. imamo četrtletni shift share in RULC narejen, manjka zapis na bazo in še dokumentacija

5. bomo razdelil še na 6. za letne. ampak tam mi niso jasni prod_A_det in prod_A_SKD. ta drugi OK, so samo top level SKD-ji. ta prvi pa so 2. level, ampak hkrati so zraven še B; D; itd, in hkrati izločen 12 (tobačni). aha, poštekala, tale tabela na SiStatu: https://pxweb.stat.si/SiStatData/pxweb/sl/Data/-/0301915S.px ima namreč nenavadno klasifikacijo po SKD, kjer so ene stvari na 1. in potem razčlenjene na 2. nivoju, ene pa samo na 1. nivoju. Tako da je zbrisala ven recimo A in C, ker sta oba razčlenjena na 2. in pustila B, ker ni razčlenjen (to so te ta brezvezni sektorji 😉)

Tako naredi potem »tidy« tabelo, se pravi se nič ne podvaja, oz. vsota vsega je vsota gospodarstva. Minus tobačni izdelki

OK, se pravi četrtletne imamo zdej prod Q in rulc Q, potem sta še tot_rulc_q in tot_prod_q, ampak slednja je samo širša verzija rulca (ki ima še rulc komponente), zato je ne bom delala. 

Potem pa je še rulc_a_q, za katerega pa ni kode, ampak tabela itak izgleda ista kot RULC_Q, tako da to tudi preskočimo... 

Se pravi imamo zdej 
SURS_shift_share_četrtletni (prej prod_q)
SURS_RULC_VA_SKD_četrtletni (prej RULC_q)
SURS_RULC_BDP_total_četrtletni (prej TOT_RULC_q)

# 3.7.2024

aha, pri eurostatu smo za četrtletje imel datume, dejmo tud pri sursu pol valda. OK, dodala. 
Zdej dokumentacijo za 05. potem pa 06, letne. 
OK, dokumentacija za 05 je ok.
dodala še linke na tabele pri skriptah, tudi za 04, treba še za ostale. 
in preveri preimenovanja tabel
in preveri podatke. 

# 4.7.2024

OK, dodala linke na tabele pri ostalih skriptah. Dodala tudi vsem lokacije prejšnjih tabel. 
Gremo še podatke preverit za nazaj.

OK, pri produktivnosti makro so agregati narobe, po moje se podvajajo jebemti. 

jesus, grem preverjat podatke, svoje in katarinine, in vidim, da se pri eurostatovih realnih dodanih vrednostih razlikujejo, ampak samo pri agregatih tipa menjalni ipd. in grem gledat v čem je fora, in je fora, da je Katarina seštevala A + B-E, jaz pa A+B+C+D+E. in se izkaže, da so B-E in G-I ipd agregati narobe izračunani na Eurostatu. AMpak samo pri realah, nominale so OK. 

OK, to je zaradi chain linked volumes-ov. zato so leta 2010 cifre ok, dlje kot greš stran, bolj se razlikujejo, ker chain linked volumes niso aditivni.. in razlike so med državami, ker se razlikujejo po ekonomski strukturi, volatilnosti, relativnih spremembah cen med sektorji ipd. ker razlike so tud manj kot en procent, pa do 10 al pa 15 % za HU, CZ, PL recimo. zdej samo ne vem kaj je bolj prav, individualne komponente al že izračunani agregati za vsote.. 

OK, preverila podatke za 02. 03.

Rotija prosila še za dva agregata tržne storitve: G-N
ostale dejavnosti: A, B, D, E, O-U.

OK, dodala oba agregata na vse NACE in SKD tabele. In v dokumentacijo povsod - manjkali sta še dva NACE šifranta, zdej je ok mislim. Preverim še podatke na 04, pol pa gremo letne sursove naprej. 

OK, preverila 04. 

# 8.7.2024

ok, letni prod so ok, preverjeni podatki tudi. 

# 9.7.2024

te letne sursove sem že trikrat okol obrnla. zdej sm vrnila nazaj ostale ravni SKD, ki so manjkale, in dodala stolpce za SKD kode in aggr stolpec. in dokumentacijo za shift share, done, za rulc skd, ok tud z rulc total. 

zbrisala belgijo iz inovatork. 

zdej je vse ok kao na prvo žogo. vse skripte so narejene, vse tabele štimajo, dokumentacija je ok. naslednji korak je task scheduler naštimat in potem to aditivnost it popravit za nazaj. trenutno so vse agregacije za države in skd-je za realne podatke napačne, ampak baje se to da prav narest, za letne lažje, za četrtletne težje, ampak bom nekak :)




# 10.7.24
prestavljanje na server ni tolk simle.. problem je source-anje iz automation scripts, ker je drug projekt in drug environment, in pol kr ene stvari ne delajo. zato bom skripto za poganjanje vsega skupaj pustila v umar-produktivnost. samo zdej me pa jebe inštaliranje eurostata in update data.table, ki se kar noče. OK, ugasnila vse procese in pol je šlo.

evo, skripti ločeni za eurostat in surs sta narejeni, batch fajla tudi, in scheduling tudi. 

baza je provizorično otvorjena. 

naslednja stvar so aditivnosti. Tale [članek](https://www.abs.gov.au/ausstats/abs@.nsf/0/95ce2d6796bd15aeca256db800754639/%24FILE/ATT4T7WF/Demystifying%20Chain%20Volume%20Measures_1.pdf) je kar super, da mi je vsaj približno jasno za kaj gre...

# 11.7.24

ok, gremo probat ta additivity. dodam, redundantly, še CLV_PCH_PRE kar je chain linked volumes percentage change on pervious period.  in PYP_MEUR, kar je previous year prices. dejmo za začetek primerjat EU 15 z mojim agregiranjem. aja, pa CP_MEUR rabim, ki so current prices, ne pa une s PPS valda.. 

OK, se pravi, imam:
tekoče cene 
stanlne cene preteklega leta
oboje je aditivno. se pravi lahko delam agregate iz tega. 
ko jih seštejem, lahko potem izračunam za agregat stopnjo rasti. in ko imam to, lahko na referenčno leto naredim chain naprej in nazaj in dobim stalne cene referenčnega leta za agregate. i think. 

# 15.7.2024

poslala Janezu write up aditivnost.Rmd, kjer mislim, da sem pravilno naredila letne agregacije iz eurostatovih podatkov. grem probat zdej še četrtletna, ki mislim, da temeljijo na annual overlap method, vsaj za eurostat, glede na metodologijo [tukaj](https://ec.europa.eu/eurostat/cache/metadata/en/namq_10_esms.htm). 

drek, grem še enkrat gledat aditivnost držav, in je pri tekočih cenah in prejšnjega leta enostavno ni. sem probala tudi EA19 za 2015-2022, ko sigurno ni tečajnih konverzij, ampak še vedno se ne seštejejo pravilno. 

unrelated: total vsote za dodano vrednost se razlikujejo glede na izvorno tabelo: a10 in a64. to velja predvsem za Irsko, Francijo in Švedsko, kjer so okoli 4% za Irsko, in okoli 0.5-1% za ta drugi dve. 

# 16.7.24

ok, napisala na eurostat pritožbo. mimgrede, [tuki](https://ec.europa.eu/eurostat/documents/24987/4253460/COMPILING-EU-ACCOUNTS.pdf) je njihov pdf z metodologijo. kjer začuda piše, da rabiš samo PYP za delat svoje CLV, ampak [tuki]( https://dsbb.imf.org/sdds/summary-methodology-base/country/EMU/category/NAG00) pa ima IMF zelo podoben tekst, ampak pravilno piše CP in PYP.

ok v excelu sprobala letne za surs, dela OK. no, sej to je bilo jasno i guess.

OK, gremo še četrtletne za surs probat. najprej aditivnost tekočih in predhodnega leta, vse ok, najs. 

# 17.7.2024

ok, ročno reverse enžiniranje četrtletnih chain linked volume-ov. kira jeba. chatgpt, claude, australski statistični biro, imf in ek. in na koncu sem nekaj spacala skupaj, ampak zgleda ok. dela samo tako, da najprej naredim chain link s prvim letom za referenco in potem rebase-am na 2010 al karkol. in še potem je treba nekaj namutit za 1. leto, ampak nekak sem. v excelu dela zdej. 

[tale](https://www.imf.org/external/pubs/ft/qna/pdf/2017/chapterv8.pdf) poglavje je bil najbolj uporaben, tabela 8.6, da sem jo reverse inžinirala, ampak še potem sem mogla za prvo leto mal namutit, samo je prav zdej. 

ok, in stvar dela ok na surs podatkih, in pol probam na "istih" podatkih iz eurostata, in wtf. se izkaže, da je CLV serija ista kot naša, ampak CP in PYP sta pa mal drugačna in to vedno bolj, bolj nazaj greš. tako da potem valda ne moraš prav izračunat CLV-ja. od 2010 naprej je ok, prej pa so vedno večji razkoraki. ne vem, grem še eno drugo državo probat. pa pizda, še dobr, da sem reverse inžinirala na sursovih podatkih, drugač bi se mi zmešal, če bi imela prav algoritm, ampak imajo oni napačne podatke... Aja, ne, to je zaradi tečajev. če uporabiš national currency, potem pa je prav. Kar pomeni, da moramo za eurostat agregacije to vedno uporabljati? Če ne niso primerljivi podatki z našimi? Al kadar agregiram eurostat agregacije, moram uporabljati MEUR series, ker piše, da so tiste suitable for aggregation and internal comparison. 

# 20.7.24

OK, razvozlavanje kako ta chain linked volume, ki ga znam v excelu narest, narest tudi v R-u sploh ni tako enostavno. Ker gre za rekurzivno serijo in dplyr ni narejen  za to v bistvu. Ampak sem po ful matranja na koncu le pogruntala. Tako da imam zdaj funkcijo `chain_linking_quarterly_2010`, ki to dela. Rabim še letno, ampak je v bistvu že narejena, samo v funkcijo jo moram spremenit.


# 22.7.24

OK, zdej pa problem: agregiranje delamo dvakrat: enkrat med SKD-ji in enkrat med državami. Ampak vsaj za Slovenijo smo zdaj vidli, da ne smeš uporabljati MEUR, ampak MNAC. Gremo najprej sprobat to v Excelu, da vidimo, če znam sploh.

# 23.7.24

OK, poskušam zdej pogrnutat kako delujejo MNAC in MEUR. za začetek sem vzela EU15, in imam za obe valuti CP, PYP in CLV. CLV meur se izračuna prav (z manjšimi napakami)za vse razen za Portugalsko, čeprav Francija in UK imata tudi malo večjo napako, ampak Portugalska gre do 1.5%... Na žalost imajo oni na svoji strani samo CLV za 2016 objavljen. OK, primerjam portugalske MEUR in njihove objavljene na njihovem sursu in so od 1999 naprej isti za current prices, prej pa so MNAC. Kar smo vidli isto velja za Slovenijo. Ampak to ne razloži zakaj so CLV na eurostatu napačni in ne sledijo izračunu iz CP in PYP.  AMpak ne morem nič kej pametnega preverit, ker itak oni nimajo 2010 objavljenega svojega. Zanimivo, če grem po SKD-jih gledat portugalsko, je B OK, A in C pa ne, niti D. E pa je spet OK. 

OK, Portugalci so očitno narobe izračunali ene svoje stalne cene. Tudi na njihovi strani, če probam njihove 2016 izračunat, so tudi narobe. Sem jim pisala. Peak geek. 

# 24.7.24

OK, čakamo na Portugalce, ampak v vsakem primeru moram naštudirat kako prav agregirat za vse države. 

OK, vzamemo M+N za vse države in aggregacije, v MEUR in MNAC za CP, PYP in CLV2010.

+ najprej check aditivnosti. CP MEUR je ok, razen za Švedsko 2022. isto CP MNAC. in oba PYPja 0.15 % približno. OK, to ignoriramo. Čeprav je čudno, ampak ne grem na Švedski Surs se zdej še tam igrat. 

+ ok, gremo zdej te tečaje gledat. Zdej če primerjamo oba CLV-ja, je kurz konstanten in sicer tist od leta 2010. Če pa gledamo CP ali PYP, pa se spreminjajo dokler je float, potem ko je pa pegged, je kurz stabilen. Aja, tudi, ko je pegged, ni stabilen, ker ERM je dovoljeval malo lufta. Zato So vse pegged valute malo spremenjlive (razen Danske it seems) Aja, Danska je v ERMII in je prostovoljno zmanjšala fluctuation band na 2.5% namesto 15Žal se teh podatkov ne da nikjer uradno dobit na enem kupu, se pravi za valute ki ne obstajajo več tipa tolar in belgijski frank. Je tud Matevž rekel, da je čudno. Ampak pač bom uporabila implicitni tečaj, ki ga dobim iz teh Eurostat objav v MEUR in MNAC, med serijami so ti tečaji isti do 4 decimalke, kar je more than enough. 

+ double check teh tečajev: isti je za CP kot za PYP (čeprav tist je seveda zamaknjen za eno leto). Isti so med serijami, recimo M, N in M_N - do četrte decimalke. tako da i guess bom to enkrat naredila in naredila nek šifrant, da je pol mir. 

+ OK, actually, i might have had it all wrong. LInki so isti ne glede na to a so izračunani iz MEUR ali MNAC. Hm, ampak mogoče je to samo pri letnih podatkih, a ne.. OK, letni zgledajo res OK. V eurostat_annual_mnac_meur.xlsx je M+N narejen ya vseh 28 plus aggregate in rayen portugalske zgleda vse prbl ok, se pravi linke lahko vzameš iz MEUR in se ne rabiš z MNAC sploh zajebavat. In dobiš iste rezultate kot so objavljeni za CLV (ki je vedno isti za MEUR in MNAC.

+ OK gremo zdej sprobat to še za četrtletne. Za Slovenijo smo že vidli, da pred 2027 ne štima iz MEUR. Za Dansko pa pred 1996 očitno. Gremo probat iz MNAC dobit prave cifre torej...

# 25.7.24

OK, gremo četrtletne za vse EU. Tukaj v bistvu ni A64, samo A10 je objavljen, se pravi lahko samo ta total primerjam, ampak je ok. 

Najprej annual averages, problem je da nekatere države nimajo podatka. Čeprav večina jih ima. AMpak kaj narest tam, kjer jih ni. Za Slovenijo podatek sicer "je", ampak je povprečje isto kot za current price, tako da mogoče sploh ni ta prav podatek, ampak je imputiran nekako?

Potem je vprašanje kaj narediš za zadnje četrtletje, ki ni celo leto? Zdaj sem vzela pač njegovo vrednost, bomo vidli kako se izzide. OK, zdadnje je OK, ampak prve 4 niso, samo ne vem kako jih pogruntat. 

  
# 29.7.24


OK, problem so predvsem 1995 letnice, ker tudi, če so podatki za PYP, kot npr za dansko in slovenijo, se linki za prvo leto razlikujejo. Kar mi ni čisto jasno zakaj, ker ostali linki so praktično identični, vsaj na prve tri decimalke. 
Anyway, iz MNAC izračunani CLV so vsi pravilni, 0.00% errorja v primerjavi z obljavljenimi.

OK, države z Eurom, recimo Finska:
+ CP so isti od leta prevzema naprej (1999)
+ PYP si isti od enega leta kasneje (2000)
+ CLV so isti za celo obdobje ?
+ CLV izračunan iz MEUR je pravilen od leta prevzema naprej 1999
+ CLV iz MNAC izračunan je pravilen za celo obdobje. 

Isto velja za Slovaško, Slovenijo. 
Torej za te države moraš vzeti MNAC CP in PYP ( jih sešteješ) in iz njih izračunaš CLV. Če imaš samo MEUR, pa rabiš preračunati v MNAC in sicer tako:
+ CP ima četrtletne tečaje, PYP pa letnega, ki je povprečje četrtletnih od prejšnjega leta. iz teh izračunaš MNAC in potem linke, cl95, cl10, clv10. 

Potem države s svojo valuto, recim oDanska:
+ cel čas MNAC v drugi valuti. Iz nje izračunaš CLV in potem ga prebaciš v MEUR. in uporabiš xrate od leta 2010..  Če ga izračunaš iz MEUR pa je tudi prav, razen za 1995. Samo ne razumem zakaj ne. 
Ampak v bistvu moram itak MNAC uporabljat, tako da je to verjetno to. Če je v EUR, potem bo CLV itak prav, za ostale pa rabim samo xrate iz leta 2010, kar pa je stalno, tako da ni nobenega overheada i guess. 

Grem probat še kako državo. Portugalska je OK razen za 1995 in malenkost 1996 (0.27%).


Se praiv rabim xrate za 2010, ki ga dobim iz CVL meur clv mnac. Dejmo to potegnt dol najprej. 

OK, imam xrates-e v 00_geo_lookup.R.

Zdej imam še annual funkcijo za CLV-je. Dela super. Zdaj je vprašanje, ali sploh downloadat CLV-je iz eurostata, če jih lahko jaz izračunam. Ali naj jih izračunamo samo za agregate. No dejmo samo za agregate, da bo hitreje?

# 30.7.24

ugh. agregiranje na geo pomeni, da je treba najprej seštet mnac-je, in za to jih moraš najprej konvertirat v meur. se pravi rabim xrates in za cp in za pyp. 


OK, se pravi takole mora it proces: imamo dve dimenziji agregiranja, po SKD-jih in po geografijah. Kazalnike imamo navadne, npr. PPS ali zaposlenost, in pa nenavadne, kot je CLV. Navadne se enostavno sešteva, ampak CLV-jev pa ne seštevaš. Za njih moraš najprej sešteti MNAC vrednosti. In če agregiraš geografije, jih moraš najprej xrate-at preden jih lahko seštevaš. Potem, ko so sešteti, pa lahko izračunaš CLV. Za aggregate SKD je torej OK, da se enostavno seštejejo vsi kazalniki. za aggregate geo pa je treba xrate. potem, ko je vse agregiranje narejeno pa pride chain linking. 


OK,

01: samo geo agregiranje
02: geo in skd aggregiranje
03: najprej samo geo agregiranje
    potem geo in skd 64 agregiranje
04: najprej samo geo agregiranje
    potem geo in skd 10 agregiranje

Zdej je trega narest geo_aggregiranje funkcijo, ki bo delala v vseh teh pogojih. predvsem je issue, ker imajo lahko input tabele različno število stolpcev. treba pa jo je znotraj funkcije dat wider in potem spet nazaj longer. Za longer pa rabim vedet število stolpcev, a ne. ki je enako številu unique v unit? probam to. OK, aggregate_geo seems to work on 1, 2, 3 and 4, that means regardless of the number of columns, and regardless if MNAC is there or not. if it is, the values are converted to Euros first. 

# 31.7.24

OK, zdej mislim, da sem v R-u prav naredila za letne, ampak se ne izzide za recimo EU15 al pa EU27. Ampak nisem prav naredila a ne, ker smo rekli, da za letne ne rabim MNAC, a ni blo tko?


OK, gremo letne še enkrat brez MNAC. Fun. OK, dela. na grafu se ful lepo ujema za 15 in 27 total. grem še procente pogledat. OK, za EU27 total je največja napaka 0.59% za 95, potem pada. Za EU15 je max 0.12% leta 1995 in tudi pada pol. This is acceptable afaic. 

OK, 01 mislim, da je OK. Samo sem morala za emp in pop dodat EU27 agregiranje, ker ga na eurostatu ni, aja, ne, problem je, da ya hrvaško ni age disagregated podatkov na pjan, tako da vse izpeljane spremenljivke, ki to uporabljajo, so šele od leta 2010 naprej. AMpak tako pač je, ne gre drugače. Za dodat v dokumentacijo. 



OK, zdej dodajam SKD-je v dvojki. in se nekaj zatakne pri malti za HTM, ker ni podatkov pred letom 2017. kako je do tega prišlo ne vem, ampak ja, če ni podatkov za 2010, pol koda seveda ne more delat.. Aha, HTM sta C21 in C26, in Malta nima podatkov do leta 2017 - do takrat so faking confidential. To pa pomeni, da ne morem izračunat CLV-jev, če nimam referenčnega leta. Tko da jebi se Malta, letiš ven. Upam, da je to edina taka fora... Mogoče če probam pogruntat kaj še manjka? Luxemburbu tudi cel kup sektorjev manjka. Drugače pa še par malenkosti, ampak nobena taka, da bi cel agregiran sektor manjkal - to je namreč issue pri MT (in LU), če ni niti enega pod sektorja, potem ni serije. Skratka to gre v dokumentacijo, kodo pa popravimo tako, da ne seštevamo stvari, ki nimajo podatkov za 2010 i guess. 


# 1.8. 

Zdej sem porabla en dan za to malto in Lux jebemti. Ampak zdej dela in če bo še komu manjkal za 2010, bo tudi delal ok. 

OK, 01 in 02 zdej delata ok.

gremo na 03, tuki je issue pri aggr in CLV, da so še D1 in D11 in D12 zraven, ki pa imajo samo CP vrednosti, ne pa tudi PYP oz. CLV, se pravi moram to nekako popucat...

OK, trojka dela, naredila double check in primerjala z originalom in so edine razlike na agregiranih geograpfijah na sedmih kazalnikih, ki imajo reale not. In to za vsa leta razen za 2010, juhej!

Hm, trojka VA check pa ima razlike tudi pri zaposlenosti, why the fuck. 

# 2.8.24

OK, double check po vrsti, v 01 so razlike tam, kjer jih ne bi smelo bit. step by step debugging. aha, EA20 je mel napa;no grupo, popravljeno. gremo 02 pogledat. 02 debugging tudi našel dve napaki, ampak zdej je OK. razlike so samo na realah in iz njih izračunanih zadevah, na nominalah in emp spremenljivkah so e-10 razlike, kar je floating point issue, efektivno je vse perfektno.
OK, 03. Evo, dela perfektno, juhej!!! aja, to je prvi del. kaj pa drugi del? tudi OK, razlike max e-09, so all good :)

# 5.8.24

ok, naredimo še SURS zdej letne, 06. Aja, ne, dejmo najprej popeglat te agregacije, ker so preveč dolge. O, clean up 01 super, pod 150 znakov. gremo naprej. Dvojka tudi OK, pod 130 znakov. 
OK, trojka. Prvi del je OK. ampak OK, zdej pri 03 pa imamo v drugem delu A10, kar pomeni, da sektorji niso več tako simple oz. natančneje, da je treba C odštet od B-E preden lahko naredimo Ostalo. Fun times. OK, zdej sem pri 3.2 morala nekaj popravljat funkcije, zato še enkrat preverjam 1 in 2. 

dodala še energetske in predelovalne brez energetskih za Rotijo. to je zdej za eurostat a64 samo. 

# 6.8.24

OK, 03.1 je ok, 03.2 tudi, s tem, da so "ostale" seveda drugačne, dodan je BDE in manjka EU27, se pravi vse super. 

Gremo še 06 za surs probat.

OK, delno ok, ampak se sesuje pri agregacijah, kjer je 2023 nula, ker backward chain ne dela.. se pravi bo treba popravit v bistvu celo funkcijo po moje. ampak jutri, ok?

# 7.8.2024

Mogoče pa ne rabim popravit, samo dodam exception za nulo. OK, je šlo tako. 6.01 dela OK, preverjeno, dodala še vse ostale skd agregacije, ki jih imamo pri eurostatu. in v skd lookup popravila list za surs det, moram to še za a10 in a64 narest. in 6.2 narest in spet preverit vse letne skripte. pol pa res dost.. 

# 9.8.2024

ok, 6.2 je tudi OK. Mislim, da je koda za letne vse OK zdej. Gremo še enkrat čez vse in sproti dokumentacijo popravimo. 
1, 2 in 31 in 32 so vsi preverjeni in dokumentacija popravljena. Samo še 61 in 62 in gremo na produkcijo. 

# 12.8.24

ok, letne so narejene, probajmo committat in it na produkcijo. stare skripte grejo v arhiv. nove se preimenujejo. 

OK, grem iz serverja pognat in zdej ene četrtletne ne delajo, wtf. sej to je že čist ok delalo od tukaj, a ni? ni mu všek dejavnosti lookup in vidim, da so čšž-ji problem. na lokalni mašini so ok. ;e dodam encoding na source, pol zgleda ok. ampak zdej je še drug problem pri eurostatu in sicer dobim external pointer invalid error za cached tabele. zato dodala povsod cache = FALSE pri get_eurostat. po moje je samo fora, da se ti temp folderji vmes zbrišejo in pol ne dela več cache. pač bomo malo bolj obremenjevali eurostatove serverje, z večkratnimi downloadi. mogoče pogledam zakaj jih sploh downloadam večkrat. verjetno so v različnih skriptah? 

ah, sploh ni blo to, ampak da sem prekinla povezavo z bazo in potem zadnji del skripte ni delal, ker mora pogledat koliko je vrstic v bazi. popravljeno zdej mensezdi. 

OK, gremo zdej četrtletja. Al najprej helper functions malo popucam in dopišem dokumentacijo tam not, da bo bolj clean. OK, narejeno.

OK, aggregate_geo_annual v bistvu dela tudi za četrtletne podatke, tako da sem popravila ime funkcije povsod. Gremo zdej CLV pogledat.. 

OK, neki je treba s tem grupiranjem narest, da je agnostično na to kaj pride not se mi zdi. ampak dost za dons..

# 13.8.24

Mogoče bi blo smart pogledat kaka je situacija pri drugih tabelah, da ne bom pol vsakič popravljala. 

OK, se pravi 

RULC_BDP_totals_Q - samo geo agregiranje
+ BDP ima NSA in SCA verziji
+ ampak po na_item imamo še D1, ki nima PYP-ja.

Aja, MNAC sem pozabla. Shit, kako že to deluje. Za skd agregacije, se pravi znotraj države, smo vidli, da moraš uporabljat MNAC, da dobiš ta prav CLV. CLV potem z 2010 xrate pretvoriš v CLV MEUR. 

Zdej, ker lahko spraviš xrate-s (dva seta sta, en za CP četrtletni in en letni za PYP), potem lahko tudi MEUR uporabljaš in pretvoriš v MNAC, da izračunaš CLV, in ga potem pretvoriš nazaj v CLV MEUR. 

Ampak vprašanje je kako delat agregacije za geo. Ker MNAC ne moreš seštevati seveda, ker so različne valute. Po moje moram v Excelu sprobat. Hm, problem je, da se CP MEUR in PYP MEUR ne seštejejo prav recimo za EU15. Razlike so do 0.12%, kar sicer ni velik. Ampak 

# 14.8.24

kurba, zdej vidim, da v enih tabelah na bazi ne delajo čšžji. Samo v drugih pa delajo, wtf? v 02 je narobe in 03 in 04 tudi. v o6 in 05 pa očitno prav. Mhm, source rabi `source("R/00_skd_lookup.R", encoding = "UTF-8")`, pol je ok tud na serverju, kjer je drgač default locale 1250.. OK, rešeno.

Gremo naprej/nazaj na četrtletne agregacije. 

OK, se pravi mamo zdej problem. in to je, da so skd agregacije pravilne z MNAC in ne MEUR. Ampak geo agregacij pa ne morem delat z MNAC seveda. Se pravi geo agregacije morajo biti iz MEUR. Poleg tega geo agregacije za CP meur in PYP meur se sploh ne seštejejo pravilno. A naredim en excel primer in jim pišem zakaj ne? Ma ja, sej to sem jim že pisala, lol. Skratka i guess se sprijaznim s tem, da geo agr so itak na prbližn, sploh če je bil kak update za posamezno državo vmes, kar pa je ful zajeban vedet al se je zgodil al ne. Res bi morala vintage shranjevat za te serije. To je naslednja stvar, dodat te eurostatove podatke na bazo... 

Ampak OK, se pravi agregiranje po dveh dimenzijah. 

# 21.8.24

ok, se pravi asociativnost in komutativnost pomenita, da je vseen vrstni red agregiranja. Ampak za četrtletja vemo, da je MNAC pravilen za sektorske agregacije. ki jih moram potem v MEUR prestavit. Potem pa geo agregacije, ki ne morejo biti perfektne, ampak so najboljše kar lahko naredimo. Se mi zdi. Gremo probat. 

OK, ampak 04 ima v prvem delu samo geo agregiranje, tako da dejmo to najprej probat i guess. OK, chainlinking za četrtletja zgleda OK, sem probala na sloveniji na hitro in od leta 2006 naprej so napake pod 0.2 milijona oz. 0.00% clean. Pa to je z MEUR, moralo bi bit z MNAC, tko da tko to zdej je.  

OK, ampak kaj narediš kadar ni podatkov za PYP za prvo leto. Takrat vzamemo CP podatke pač...

OK, še en problem: zadnji kvartal. kaj narest, ko ni za vse države podatkov. in dodatna čudna zadeva: kako imajo lahko objavljene podatke za CLV ne pa za CP. recimo EE za Q2 2024. Aha, to je "estimated", čeprav je glupo, da estimateajo samo CLV ne pa tud ostalih.. Hm, get_eurostat ne pusti keep flags opcije, če so filtri. tako da bi morala bulk downloadat vse, če bi hotela obdržat tudi filtre. 

Glede agregiranja z manjkajočimi mogoče pa ne brišem NA-jev, pa bo agregacija pustila NA. 

OK, agregacije za geo delajo ok zdej, samo preveč NA-jev not ostane, to je treba popucat jutri... 

# 22.8.24

Jesus, ok, tuki je neki ful narobe.. bdp za agregirane geo je čist off, indeksi padajo dramatično, wtaf.. Aja, ponesreč sem annual namesto quarterly funkcijo dala, vse je OK, phew.

OK, zdej pa še tole: zakaj ni SCA EU13 podatkov? Aha, ker manjka Malta. V bistvu zato tudi ni podatkov za Eu13 do leta 2000, ker manjka Malta. Prej nismo teh NAjev upošteval in se je seštelo ne glede na to al so bli podatki za vse države al ne. Zdej sem to dala stran, kar mislim, da je edino pravilno, tud če to pomeni, da ene serije ne obstajajo al pa so krajše. 

Zdej recimo Malta nima PYP podatkov desezoniranih sploh. So pa podatki za CLV. Samo kaj naj s tem, ne moremo pri enih serijah prištevat zraven CLV-jev, pri drugih pa ne. Pač ne bo podatka. 

OK, ampak zdej pri EU14 nimam serije, ker italija nima CLV-ja za 1995. in jaz sem dala za pogoj, če ni PYP-ja ampak je CLV, da se uporabi CP. Ampak tega ne smem očitno, ker je lahko brez CLV-ja. al pa moram začeti serijo šele tam, kjer je CLV? Ker eurostat ima serije od 95 naprej tudi za EU27 ali 28, kjer je Italija not. OK, popravila. 

Še vedno ni SCA serije, zato ker PYP ni objavljen za SCA, čeprav CLV pa je, kar je čudno. Aja, verjetno desezoniraš CLV direktno. 

OK, gremo tele države, ki manjkajo popravit še v letnih podatkih verjetno, a ne?

Aja, najprej dejmo še to: če za eno celo serijo ni podatkov, se pravi celotno obdobje so NA, jih vržemo ven, a prav? Mogoče ne, al pa bom Rotijo vprašala. 

OK, geo agregiranje za četrtletja dela OK. Gremo SKD-je pol gledat? Za to rabim MNAC-e. 

# 23.8.

prva runda četrtletij zgleda da daela. 

# 26.8.2024

popravek na 05 sursu, kjer je bil s stroški dela narejen nepopolen merge, ker so bila imena dejavnosti narobe. opazila Rotija, da manjkajo comp podatki za originalne dejavnost. zdej ok. 


OK, 04 zgleda ok, gremo na 05. 

OK, mislim, da je 05 tud ok, preverim jutri in dokumentacijo porihtam.

# 27.8.24

OK, odokativno vse 05 tabele zgledaj OK. Gremo še preverit zares 04 in 05. V iz štirke ima razlike pričakovane edino EA20 ima ful razlik tudi na kazalnikih, ki jih ne bi smel imet, kako je do tega prišlo pojma nimam. Aha, ker sem imela napako tam, lol, vse kul zdej. 

OK, vse zgleda kul. Gremo še dokumentacijo in to je to. Aja, commit prejšnje verzije in potem nove .


Poglej pol še za ostale skripte, če so geo agregati vedno popolni!

Aha, manjka mi BDE pri štirki, zato so Ostali narobe, kako sem to spregledala pitaj boga. OK, še to. 
OK, mislim, da je OK.

Dej še polinkaj skripte na tabele v dokumentaciji. OK. In dokumentacija je ready po moje. Samo nikjer ni razloženo, da je MNAC uporabljen pri eurostat četrtletnih agregacijah. OK, vsaj tukaj je zaenkrat. 

Grem pogledat še geo agregacije pri letnih, če so OK. Ja, ni na.rm je true, tako da ma da je OK. 


Dobro, to je zdej na produkciji, uradno otvorjeno. Upam, da dela vse ok, bomo vidli sprot. za zdej imam dost.




# 13.9.2024

dodala-začasno tabelo za letni surs shift share, kjer je namesto sursovega skupaj, vzeta Katarinina verzija skupaj, ki izvzame sektorje 12 tobačna, pripisana stanovanjska dejavnost gospodinjstev v L. in O . dejavnosti uprave in obrambe..in U dejavnosti extrateritiorialnih..

dodana nova tabela shift_share_teoretsko_prav. in začasno nova skripta samo za to verzijo tabele, po posvetovanju z Rotijo, Urško Č in Janezom bomo naredili permanentno in posodobili dokumentaicjo. 


# 5.2.2026

Rotija prišla prosit, da poženem eurostat, ker je Peter preračunaval s podatki tam in so drugačni kot naši. ker smo mi nazadnje 17.12. posodabljali in na eurostatu vmes posodabljajo stvari za posamezne države, tko da tko pač je. sem pognala še enkrat, ampak ni delalo, ker so vmes že za ene par džav za 2025 objavili podatke, ampak ni pa seveda še EU27 izračunanega, ki ga rabimio, sem mogla mal popravit pipe v 01.

potem sem pa še iz https://ec.europa.eu/eurostat/news/release-calenda pobrala vse data release objave z GDP jem in jih dodala v task scheduler. 


